version: '3'

services:
  analysis_env:
    build: .

    container_name: analysis_env

    user: root

    privileged: true
    
    volumes:
      - "./workspace:/home/jovyan/work"

    command: sh -c "sleep infinity"